[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
build = "build.rs"
name = "leap"
version = "0.1.0"

[build-dependencies]
cmake = "0.1.17"

[dependencies]
libc = "0.2.14"

[dev-dependencies]
rustbox = "0.8.1"
